### ISSUE TITLE
Mavlink 2 support

### ISSUE THREAD

**Issue by RespawnDespair** [RespawnDespair/wifibroadcast-image-builder#35]
Change library to mavlink v2 in all repositories and recompile.

**Comment by dposea** [comment]
Where will things like the mavlink library, mavlink header files, etc. be kept? A lib directory and an include one should be enough. Any builds would just point to those. You did a great job on the image_builder btw!!

**Comment by Yes21** [comment]
**@RespawnDespair** 
Is this related to MavLink 2.3 support from careyer/dino.de ?
Are you coordinated with them ?

**Comment by careyer** [comment]
I am happy to see this feature on the list. Please reach out to me if any help is needed. Introducing MavLink v2 was not just a matter of recompiling it with new headers. dino.de struggled a long time because there was a buffer overflow error somewhere after the recompile which resulted in a non working build. Also the concept of Ground- and AirSwitches nicely integrates with it and makes full use of the 24Channels that are read as an input from the Joytsick/Taranis.

For your convenience I will once again include the link to the image with all MavLink related stuff already working: https://www.dropbox.com/s/yzavlwsfrcbys57/EZ-Wifibroadcast-1.6RC6_FlirOneG2_v0.9_omxh264_MavLinkv2_GPIO.img?dl=0

Cheers!

**Comment by RespawnDespair** [comment]
Thank you very much, i have been asking around for that image!
Is there any way to reach dine.de directly?

**Comment by careyer** [comment]
@RespawnDespair : You are welcome! He also has a Github Account https://github.com/dino-de . He has little time now to code because of family reasons but he said he would be there and happy to answer any questions so they might arise. Maybe you can invite him to the repository or something to get in contact?

**Comment by RespawnDespair** [comment]
I'll contact him trough github. I'll analyze the image first and then see what questions remain.
Thanks!

**Comment by careyer** [comment]
Great! for the changes made to .profile you might want to search for the keywords "switch" or "switches" (this is the GroundSwitches mimic - in this image it switches between two video streams that are transfered in parallel in videofifo1 and videofifo5) and for "airswitches" (this is the GPIO mimic for the AirPi . in the image it switches the GPIOs 17 and 18 via the Channels 15 and 24 I believe.) Pretty straight forward. All the Mavlink stuff should be reflected by changes in the filesystem

**Comment by careyer** [comment]
I asked dino.de. It is totally fine for him if you ask him.... I can share his email when needed

**Comment by dposea** [comment]
It looks like you already picked up most of his code changes. I'm testing a different version of the rtl8812au driver using the image builder image from a few days ago. It was working on the airpi side to transmit video. I have not tried any other functions yet because I'm busy trying to build non chibios versions of ardupilot, and having problems.  I think I understand the build system and it looks like they just replaced nuttx. You cant just check out something like plane 3.9 either. All of the submodules need to be checked out separately, but on the same day and close to the time of plane 3.9 (example) . Otherwise the code needed for the build doesn't match.

**Comment by Yes21** [comment]
**@dposea** 

> I'm testing a different version of the rtl8812au driver using the image builder image from a few days ago. It was working on the airpi side to transmit video.

What version ? 5.3.4 ?

**Comment by RespawnDespair** [comment]
I have updated all repos to build using the latest Mavlink v2 libraries.
This is all in the 'staged' branche of the image builder.
I will release a new test image a.s.a.p.
