### ISSUE TITLE
Kernel .config not applied

### ISSUE THREAD

**Issue by rodizio1** [RespawnDespair/wifibroadcast-image-builder#56]
It seems the kernel configs (https://github.com/bortek/EZ-WifiBroadcast/blob/develop/kernel/v7-kernel-config and https://github.com/bortek/EZ-WifiBroadcast/blob/develop/kernel/v6-kernel-config) are not applied to the kernels before building.

This is important, because there are settings that must be changed (Hz timer for example, with the default 100Hz , scheduling is too jittery which leads to packetloss with multiple RX dongles). Also, the changed config files have a lot of stuff disabled which speeds up boot-time on the raspberry, uses less memory on the Raspberry and also speeds up the building of the kernel a lot.

The config files from the above directories are for 4.9.35 though, so won't work for 4.14.x.

I have configs for some older 4.14. kernel version, I'll see that I update those for the agreed-on 4.14.71 kernel release and supply them somewhere.

**Comment by RespawnDespair** [comment]
Oh and let me add: THIS IS WHY I'M HAPPY YOU ARE BACK!
I spent hours trying to figure out all the different changes, where you have a deeper insight to what makes EZWFB work. So thanks again for checking!

**Comment by rodizio1** [comment]
I looked into the files, they seem to be pretty much "default", i.e. no changes to the timer ticks settings as well as a lot of unnecessary stuff built-in.

I don't know all the changes by heart, but like I said, I already have .configs for 4.14. kernels, it's just a matter of using those and running "make oldconfig" to include new/changed settings that have been added/changed between the (early) 4.14. release I used some time ago for testing and the (late) 4.14. release that is now being used in the image.

**Comment by RespawnDespair** [comment]
I would love to do that, there are also some settings regarding the RTL88xx driver that need to be added.
Do you have these 4.14 files? I could try to 'merge' the changes into those and build again with the optimized kernel.
I'm hopeful that will fix most of the latency issues.

**Comment by rodizio1** [comment]
Yes, I can supply them later when I get home.

There are settings in the kernel .config file for the RTL88xx drivers? I thought they have their own source-tree.

**Comment by RespawnDespair** [comment]
They did, but it was more effecient to include them in the kernel stage, works like a charm. 
First time we have working RTL88xx support in the newer images.
If you provide the configs i'll merge them and create and upload a new image tomorrow.
Then we'll test if that's the fix for a latency issues.

**Comment by RespawnDespair** [comment]
I will try to implement this, also looking at the packages in the image that need to be removed.
I go on vacation tomorrow untill monday, so i'll probably wont have time to work on this.
Next week should see some major steps if i can get the kernel optimizations correct and the interfering packages removed.

**Comment by rodizio1** [comment]
Regarding the packages to be removed: Running "dpgk -l" on the original 1.6RC6 image and on the new image builder image and then diffing the output should give a first overview. Although it's not perfectly comparable because the image builder uses a much newer Raspbian version based on a newer debian version, things probably have changed there.

**Comment by RespawnDespair** [comment]
I have made new kernel configs for v6 and v7. They are in stages/02-kernel/FILES. 
@rodizio1 could you take a look? I'm building a new image now to see if it boots at all...
Lots of things were different from the 4.14.32 config so i had to guess some settings...

**Comment by rodizio1** [comment]
Did a quick test yesterday. Pi3B seems to work (tested with CSL300 mbit RT5572 stick), however with a Pi3B+ it would crash/hang while trying to initialize the stick.

**Comment by pilotnbr1** [comment]
So a couple observations regarding these config settings. 

On boot and boot logs the cpu does seem to be set correctly to 900mhz

Mounting a 2.0 image on my laptop and looking at the config.txt file I see things missing still and the cpu freq shows 700mhz which disagrees with what happens when you boot a live image as above. So not sure how to reconcile these differences-- more poking around

Mounting a 1.6 image on my laptop shows these settings-


----------------------------------------------------------------------------------------------------------------------------------


# General note: You can find more info on the options in this file here:
# https://www.raspberrypi.org/documentation/configuration/config-txt.md

# uncomment if you get no picture on HDMI for a default "safe" mode
#hdmi_safe=1

# uncomment this if your display has a black border of unused pixels visible
# and your display can output without overscan
disable_overscan=1

# uncomment if hdmi display is not detected and composite is being output
# also set this in conjunction with a specific HDMI mode below if you want
# to connect your display when the Raspberry is already running, i.e. the
# display has not been connected during power-up
#
#hdmi_force_hotplug=1

# uncomment to force a specific HDMI mode
#
# 640x480
#hdmi_group=1
#hdmi_mode=1
#
# 800x600 Fatshark HD1/2/3 (4:3)
#hdmi_group=2
#hdmi_mode=9
#
# 1024x768
#hdmi_group=2
#hdmi_mode=16
#
# 1280x720 Fatshark Base HD
#hdmi_group=1
#hdmi_mode=4
#
# 1280x800 Headplay HD
#hdmi_group=2
#hdmi_mode=28
#
# 1280x1024
#hdmi_group=2
#hdmi_mode=35
#
# 1440x900
#hdmi_group=2
#hdmi_mode=47
#
# 1680x1050
#hdmi_group=2
#hdmi_mode=58
#
# 1920x1080 Goggles One/Two
#hdmi_group=1
#hdmi_mode=16

# Topfoison 6" 1080x1920 display
#hdmi_ignore_edid=0xa5000080
#max_framebuffer_width=1080
#max_framebuffer_height=1920
#display_rotate=3
#hdmi_timings=1080 0 118 4 118 1920 0 4 4 3 0 0 0 60 0 152940000 3
#hdmi_group=2
#hdmi_mode=87

# OSVR HDK 1.4
#[EDID=SVR-OSVR_HDK]
#hdmi_ignore_edid=0xa5000080
#hdmi_group=2
#hdmi_mode=87
#hdmi_timings=1080 0 32 5 11 1920 0 12 5 6 0 0 0 60 0 131000000 3
#display_rotate=3
#max_framebuffer_width=1080
#max_framebuffer_height=1920

# uncomment to increase signal to HDMI, if you have interference,
# blanking, or no display
#config_hdmi_boost=4

# uncomment for composite PAL
#sdtv_mode=2

# Enable audio (loads snd_bcm2835)
dtparam=audio=off

# Enable camera
start_x=1
gpu_mem=128

# force gpu to run in turbo mode for less latency and jitter
force_turbo=1

# Set CPU speed to 900Mhz
arm_freq=900

# Set higher voltage for stability
over_voltage=3

# overclock CORE/GPU/SDRAM for less latency and higher data troughput
gpu_freq=400
sdram_freq=433

# speed-up booting
bootcode_delay=0
boot_delay=0
disable_splash=1

# allow for maximum 1.2A current on USB bus
max_usb_current=1

# disable Bluetooth on Pi3 so that the GPIO serial port is usable
dtoverlay=pi3-disable-bt

# needed for serial port, otherwise /dev/AMA0 does not exist
enable_uart=1

# reduce maximum USB hub depth to 2
usb_mdio=0x7000

# test, don't change
#hvs_priority=0x32ff
#
# uncomment for I2C
#dtparam=i2c1=on
#dtparam=i2c_arm=on
#
# uncomment for SPI
#dtparam=spi=on

**Comment by RespawnDespair** [comment]
I will compare and replace the version in overlay. Thanks for the check!

**Comment by RespawnDespair** [comment]
@pilotnbr1 The file:
https://github.com/RespawnDespair/wifibroadcast-image-builder/blob/master/stages/04-Wifibroadcast/FILES/overlay/boot/config.txt

is exactly the same as the one posted here, so i do not know which 2.0 image you mounted, but if it was a recent build, something is going wrong...

**Comment by pilotnbr1** [comment]
It was a recent build.. Hmm must be something wrong on my side

**Comment by RespawnDespair** [comment]
I have verified the correct config is placed on the boot partition in an image.
Closing this issue to keep things clean.
