### ISSUE TITLE
Problem with ETHERNET_HOTSPOT=Y

### ISSUE THREAD

**Issue by Yes21** [RespawnDespair/wifibroadcast-image-builder#60]
When ETHERNET_HOTSPOT is set to Y, it becomes impossible to ssh with the groubdPi  on 192.168.0.18, and the groundPi is unreachable at 192.168.1.1 (which is supposed to be its IP with ethernet hotspot).

**Comment by rodizio1** [comment]
When ethernet hotspot is enabled, the Pi should have IP 192.168.1.1, and your PC should have received the IP 192.168.1.2 by the dhcp server running on the Pi.

Can you confirm that your PC got 192.168.1.2? Another idea would be switching to TTY8 (or was it 9? Not sure right now) to see what's going on there, it should tell you when it has detected a client connected.

**Comment by Yes21** [comment]
With **ETHERNET_HOYSPOT=Y** I can't anymore ping 192.168.0.18, nor 192.168.1.1. nor 192.168.1.2.
I can see that the groubdPi's IP is 192.168.1.1. From the Pi, I can't ping 192.168.1.2.
On tty11 (eth0 DHCP client) I can see "Ethernet Hotspot enabled, doing nothing".
This should be a bug ...

**Comment by dposea** [comment]
soemwhere I'll bet the command pump -i eth0 is not getting run. When testing I add it to /root/.profile to make sure I can ssh in via ethernet. Wait, for an ethernet hotspot I think hostapd is used instead. wpa_supplicant is not even installed. I'm not all that good with network stuff. I put a static ip for eth0 in /etc/network/interfaces and used pump because I was not getting an ethernet connection when plugged into my router. One possible problem is many routers already use 192.168.1.1.  Using 10.0.0.1 for the hotspot may be better, or even 10.40.0.1

**Comment by rodizio1** [comment]
@dposea, you are talking about the ethernet _client_ functiality, not ethernet _hotspot_.


@Yes21 TTY11 is about ethernet _client_ functionality, you need to look on TTY8 for messages regarding the hotspot functionality. The message you see ("ethernet hotspot enabled, doing nothing") just says that the ethernet _client_ functionality is not being used because the hotspot functionality has been enabled by the user.

If you say "switch" I assume you somehow have everything connected to your home-router/switch?  The idea behind ethernet hotspot is, that the Pi basically becomes the "router" (actually, it doesn't route anything) or the device that hands out IP-addresses. The intended use is:

1. Start-Up Raspberry
2. Plug-in another computer (or Pi) via ethernet via direct cable connection

Does that work?

**Comment by Yes21** [comment]
@rodizio1 
Sorry, I never understood that in that way !!
Now Yes, it works when the Pi and the pc are directly wired with a RJ45 cable ...
Thanks

**Comment by Yes21** [comment]
I've updated the wiki with this explanation.
I close the issue.
