### ISSUE TITLE
Strange problem with kernel headers

### ISSUE THREAD

**Issue by Yes21** [RespawnDespair/wifibroadcast-image-builder#67]
One needs to install kernel headers to compile a kernel module (aircrack-ng/8812au v5.3.4) :
`sudo apt-get install raspberrypi-kernel-headers`

With a regular 2018-10-09-raspbian-stretch-lite, this command creates these directories :
```
/usr/src/linux-headers-4.14.71+
/usr/src/linux-headers-4.14.71-v7+
```
Then the driver can be compiled and works.

But with our script built image, these directories are created :
```
/usr/src/linux-headers-4.14.79+
/usr/src/linux-headers-4.14.79-v7+
```
Then the driver can be compiled but can't be loaded (modprobe: ERROR: could not insert '88XXau': Exec format error).

So I can't understand why the 4.14.79 kernel headers are installed in place of 4.14.71, with our built image ??

I hope someone will be able to solve this mysterious issue ...

**Comment by rodizio1** [comment]
The script is probably pulling the latest Raspbian which is 2018-11-13 (with kernel 4.14.79) since a few days, but the kernel sources are 'hardcoded' to 4.14.71 and thus the mismatch.

**Comment by RespawnDespair** [comment]
The image builder has the image defined in the `config` file in the root.
The current master version has `2018-10-09` as the image and the SHA for the kernel headers is `4f30a5365296658d66ef8a9f878a25d229e2d5fa` which should correspond with the headers used in this image. (they do for me)

What you are doing is pulling the latest kernel headers on an image with a different kernel and headers installed. The right course of we want the new RTL88xx on the image is to build it DURING the creation of the image, that's how the system is designed to work. Not to modify the generated image itself. Then we are back to manually altering images and distributing different images.

I know you really want this to work and so do i, but as @rodizio1 confirmed, neither 5.2.2 or 5.3.4 works without issues. Once we settle on which version is the 'least bad' i will make sure the generated image compiles with that version. There really is no need to keep trying to post-integrate other drivers.

I originally used the 5.3.4 because it was the latest and was then urged to move back to 5.2.2 because this would be more stable. If something has changed in that situation i will move back to 5.3.4.

**Comment by Yes21** [comment]
I know what you mean, and I agree with you.
The script is very well done, and I don't want to ask you to modify it only for my test.
I don't know if we should move from 5.2.20 to 5.3.4, but I want to test 5.3.4 with my AWUS1900. @rodizio1 did test only with AWUS036ACH ...
If I don't see any improvement with AWUS1900 and 5.3.4, I well tell you we have any interest to move to it ...
Many thanks for the great job you did, and will do.
Don't give up !
Yves

**Comment by Yes21** [comment]
I finally succeed in compiling the 5.3.4 kernel module !

I did need to copy the `/usr/src/linux-headers-4.14.71-v7+` from the  regular 2018-10-09-raspbian-stretch-lite to my built image. Then I had to create the good symlink in `/lib/modules/...`

I know that's not a clean way, but that's the only one I did find ...

Nevertheless I think that it's not normal that with the built image a wrong version of kernel headers are installed by `sudo apt-get install raspberrypi-kernel-headers`. This not occurs with a regular raspbian image ...
So something must be wrong somewhere !

But I know that's not so important, and not a priority to fix it.

**Comment by Yes21** [comment]
I've understood and could fix this issue :

Just commenting these 3 lines 
```
# sudo rm -rf /var/lib/apt/lists/*
# sudo apt-get clean
# sudo apt-get update
```
It will be in my next PR.

**Comment by RespawnDespair** [comment]
I will reply to just this one issue, but thank you very much for your efforts, i have merged the PR!

**Comment by Yes21** [comment]
Before removing `sudo apt-get update` not only kernel headers and sources were pointing to next raspbian version (4.14.79), but it was also true for all packages. And I could see many uninstalled packages in apt logs (/var/log/apt).
Now we have 0 uninstalled packages, and this could perhaps resolve others issues ??
We'll see ...
