### ISSUE TITLE
Raspbery Pi3 B+

### ISSUE THREAD

**Issue by DPiperkov** [RespawnDespair/wifibroadcast-image-builder#9]
Hi,
I'm trying to make image for my Pi3 B+.
After finish i have 4 images
2018-6-27-raspbian-stretch-lite.img
2018-6-27-raspbian-stretch-lite.zip
2018-6-27-raspbian-stretch-lite_2018-09-12.img
temp.img

i was trying every image and no one work 
every image is clear raspbian
how I can make image

I'm using Ubuntu 18 for making image
Thanks.

**Comment by RespawnDespair** [comment]
The 2018-6-27-raspbian-stretch-lite_2018-09-12.img should be the output image, there are however some problems with the code right now. I need to fix the loading of the config file. The image will dump you to a login prompt right now...

**Comment by DPiperkov** [comment]
OK but i can't see wifi_broadcast directory in this image for trying to starting it manual

**Comment by RespawnDespair** [comment]
/home/pi should contain a lot of WFB related folders.

**Comment by DPiperkov** [comment]
Thanks
Now i flash that image and i'll try again.

I using 
 cat /root/telemetryfifo1 | /tmp/osd >> /wbc_tmp/telemetrytmp.txt
for starting osd

**Comment by RespawnDespair** [comment]
I am unsure if the OSD is still compiled to /tmp, i've tried to optimize some of the more arcane steps during boot, but it appears that some bugs have crept in. Due to the fact i don't have any test equipment anymore (magic blue smoke, don't want to get into details) i can't test much at the moment. New stuff is underway, but i'm relying on other people to do the testing right now.

**Comment by DPiperkov** [comment]
Understand.
Thank you for your work.

**Comment by RespawnDespair** [comment]
Closing this as testing shows the basics work on the Pi3B+ now.
Edge cases may still exist, but we need specific issues for those.
